T_camera_to_base:
- - -0.024578704848259716
  - 0.47407040258123073
  - 0.8801438181709007
  - -1.193571757497472
- - 0.9995846716965542
  - -0.0015960969342680197
  - 0.02877388718731399
  - -0.3592953850452695
- - 0.015045643132614382
  - 0.8804854944126257
  - -0.473834277729756
  - 0.5816867642206844
- - 0.0
  - 0.0
  - 0.0
  - 1.0
