T_camera_to_base:
- - 0.15421239495981864
  - 0.5563017298464793
  - 0.8165457259765503
  - -0.8423169197980176
- - 0.9880023427126324
  - -0.07983062614035633
  - -0.13220605857671092
  - 0.44444596748513454
- - -0.008361102505469453
  - 0.8271369031181317
  - -0.5619382843916576
  - 0.7891489721994204
- - 0.0
  - 0.0
  - 0.0
  - 1.0
base_offset_mm:
- 10.0
- 9.999999999999996
- 190.00000000000003
base_rpy_deg:
- -2.000000000000001
- 1.9999999999999993
- -4.000000000000001
