camera:
  workspace_roi:
    depth_max_mm: 18857
    depth_median_mm: 8889
    depth_min_mm: 6328
    points:
    - - 801
      - 452
    - - 1042
      - 10
    - - 17
      - 46
    - - 285
      - 453
    resolution:
    - 1280
    - 720
    type: polygon
