camera:
  workspace_roi:
    depth_max_mm: 18857
    depth_median_mm: 8889
    depth_min_mm: 6328
    points:
    - - 1043
      - 13
    - - 15
      - 53
    - - 262
      - 405
    - - 817
      - 434
    resolution:
    - 1280
    - 720
    type: polygon
